title: Joheb Shaikh
logo: /Img/headshot_200x200.jpeg
description: Data analyst focused on delivering insights that drive business growth and innovation
show_downloads: true
theme: jekyll-theme-minimal
