title: Joheb Shaikh
logo: /GitHub Repository/headshot_200x200.jpeg
description: Passionate about turning complex data into actionable business insights
show_downloads: true
theme: jekyll-theme-minimal
